### ISSUE TITLE
シルク番号の不一致

### ISSUE THREAD

**Issue by Diwamoto** [sekigon-gonnoc/ec-switch-scan-module#1]
# 概要

こんにちは。Diwamotoと申します。

こちらのモジュールのシルク番号が違うのではないかと思い、私が動作確認が取れたファームウェアとkicadのファイルを添付いたしますので、確認をお願いできますでしょうか。
もしくは、今回私はスキャンラインから任意で選択してファームウェアを実装したのですが、そちらは想定されていない動きでしょうか？

# 確認バージョン
QMK_firmware→[dev/sekigonブランチの最新バージョン](https://github.com/sekigon-gonnoc/qmk_firmware/tree/dev/sekigon)
静電容量モジュール→2021年9月初頭にboothにて購入

# 内容

添付ファイルを見ていただければと思いますが、[こちらの資料](https://github.com/sekigon-gonnoc/ec-switch-scan-module)を読みながら以下のように割り当て、配線しました。
col0 | col1 | col2 | col3 | col4 | col5 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
S8 | S6 | S4 | S1 | S2 | S3 

ファームウェアの`MATRIX_COL_PINS`についても、合わせて以下のように実装しました。
```c
#define MATRIX_COL_PINS  { S8, S6, S4, S1, S2, S3 }
```
ですが、この状態だとcol0とcol1が動作せず、QMK_ToolBox上で`ecsm_dprint_matrix()`でも確認しましたが、静電容量の変化は見られませんでした。実際に動作したのは以下の定義です。
```c
#define MATRIX_COL_PINS  { S7, S5, S3, S8, S1, S2 }
```
このように定義することで、`keymap.c`に記載がある通りに動作しました。

ファームウェアはGRS-70ECのものを使わせていただいており、そちらをコピペしたものから設定などを変更して動作確認しております。

確認の為に必要な事項等ございましたら添付いたしますのでお申し付けください。

よろしくお願いいたします。

**Comment by Diwamoto** [comment]
[daughter.zip](https://github.com/sekigon-gonnoc/ec-switch-scan-module/files/7212378/daughter.zip)
こちらがkicadで作成した基板データです。

**Comment by Diwamoto** [comment]
[ttest.zip](https://github.com/sekigon-gonnoc/ec-switch-scan-module/files/7212382/ttest.zip)
こちらがその基板で動作確認が取れたファームウェアになります。

**Comment by sekigon-gonnoc** [comment]
基板が1-indexedでソフトが0-indexedになってしまっているのでシルク表示そのままで設定すると1つずれてしまうようです。

申し訳ありませんがファームの定義を変えるなり読み替えるなりして対応してください

**Comment by Diwamoto** [comment]
@sekigon-gonnoc 
なるほど、そういうことだったんですね。
ありがとうございます。
